### ISSUE TITLE
need to display supporting python version 

### ISSUE THREAD

**Issue by AhnSeongHyun** [bgusach/pyconstring#1]
> sudo pip install pyconstring
You are using pip version 7.0.1, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pyconstring
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading pyconstring-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-s0YDcF/pyconstring/setup.py", line 7, in <module>
        import pyconstring
      File "pyconstring/__init__.py", line 2, in <module>
        from .pyconstring import (
      File "pyconstring/pyconstring.py", line 18
        self._formatted_prio_keys = {self._format_key(k) for k in self._non_overridable_keys}
                                                           ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-s0YDcF/pyconstring

Dict comprehension is supported from Python 2.7 .

**Comment by bgusach** [comment]
Hello,

what would be the appropriated place for this information? just the README?

Thanks for the feedback.
